ktor:
  deployment:
    port: "$PORT:8080"
  application:
    modules:
      - com.kanjimasta.ApplicationKt.module

firebase:
  projectId: "$FIREBASE_PROJECT_ID:demo-kanji-masta"
  authEmulatorHost: "$FIREBASE_AUTH_EMULATOR_HOST:"

claude:
  apiKey: "$CLAUDE_API_KEY:"

gemini:
  apiKey: "$GEMINI_API_KEY:"
