ktor:
  deployment:
    port: 8080
    port: ${?PORT}
  application:
    modules:
      - com.kanjimasta.ApplicationKt.module

database:
  host: "127.0.0.1"
  host: ${?SUPABASE_DB_HOST}
  port: "5432"
  port: ${?SUPABASE_DB_PORT}
  name: "postgres"
  name: ${?SUPABASE_DB_NAME}
  user: "postgres"
  user: ${?SUPABASE_DB_USER}
  password: "postgres"
  password: ${?SUPABASE_DB_PASSWORD}

jwt:
  secret: "super-secret-jwt-token-with-at-least-32-characters-long"
  secret: ${?SUPABASE_JWT_SECRET}
  issuer: "https://omuhcbxjtjyzzvznhvib.supabase.co/auth/v1"
  issuer: ${?SUPABASE_JWT_ISSUER}

claude:
  apiKey: ${?CLAUDE_API_KEY}